---
title: "Data Science CPD Training Courses"
author: "Mark Andrews"
date: "12th January, 2023"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Training courses in 2023

* In 2023, I will be teaching the following six courses:

  * Introduction to R (two day course; April 2023)
  * Data wrangling in R (two days; April 2023)
  * Data visualization using R (two days; May 2023)
  * Generalized linear models (two days; May 2023)
  * Multilevel models (two days; June 2023)
  * Bayesian data analysis (three days; June 2023)
  
* These courses are aimed at scientists and researchers, most of whom have, or are obtaining, a PhD.

## For data science, the future is CPD

* Data science and computational statistics is evolving exponentially.
* For example, around 20 to 25 years ago, 
  * scientific computing was around $\approx 10^5$ less powerful
  * the world's most powerful computer would have cost around £1 billion and would be equivalent to one of today's affordable scientific workstations
  * R was almost unheard of. Now, R has around 20 million regular users and is one of the most popular programming language in computing.
* As a consequence of this rapid growth, learning statistics and data science just once, early in one's career, is not an option if one is to remain competitive.

## Data science CPD market: demand, supply, and other issues

* Many people in need of data science CPD training are not aware of their needs.
* In general, marketing and advertisement is not trivial. Rising above the din in social media is difficult; reputation and word of mouth matters a lot.
* The market does not seem to be in danger of excess supply.
* Nor does the market appear in danger of being a winner-take-all market.
